# why Numpy

In [1]:
# occupy lesser memory, contagious memory, SIMD Vectore processib, Effective cache utilization

In [2]:
#The Basics

In [3]:
import numpy as np

In [26]:
a=np.array([2,3,5],dtype='int32')
print(a)

[2 3 5]


In [41]:
b=np.array([[2,5.4,7,23], [8,4.2,6,1]])
print(b)

[[ 2.   5.4  7.  23. ]
 [ 8.   4.2  6.   1. ]]


In [16]:
#Get the shape
a.ndim

1

In [17]:
b.ndim

2

In [18]:
#Get the shape
a.shape

(3,)

In [19]:
b.shape

(2, 4)

In [31]:
a.dtype

dtype('int32')

In [28]:
#Get the size
a.itemsize
b.itemsize

8

In [29]:
#Get the total size
a.size

3

In [30]:
a.nbytes # = a.size * a.itemsize

12

# Accessing and changing specific elements in rows,colums etc

In [2]:
import numpy as np
a=np.array([[1,2,4,5,7], [3,8,9,4,1]])
print(a)

[[1 2 4 5 7]
 [3 8 9 4 1]]


In [5]:
#get a specific elemts[r,c]
a[1,3]

4

In [6]:
#Get a specific row
a[0,:]

array([1, 2, 4, 5, 7])

In [7]:
a[:,1]

array([2, 8])

In [11]:
#Getting a little more fancy [startindex, stopindex, step]
a[0,1:4:1]

array([2, 4, 5])

In [14]:
a[1,4]=27
a[:,2]=[30,12]
print(a)

[[ 1  2 30  5  7]
 [ 3  8 12  4 27]]


In [15]:
a[0,2]

30

#3d examples 

In [19]:
b=np.array([[[1,3],[8,11]],[[2,3],[6,4]]])
print(b)

[[[ 1  3]
  [ 8 11]]

 [[ 2  3]
  [ 6  4]]]


In [20]:
b[:,0,:]

array([[1, 3],
       [2, 3]])

In [21]:
b[:,1,:]

array([[ 8, 11],
       [ 6,  4]])

In [22]:
b[:,:,1]

array([[ 3, 11],
       [ 3,  4]])

In [26]:
b[1,0,1]

3

In [28]:
#Replace
b[0,1,:]=[9,11]
print(b)

[[[ 1  3]
  [ 9 11]]

 [[ 2  3]
  [ 6  4]]]


In [31]:
b[1,0,:] = [8,11]
b[1,:,1]=[4,3]
print(b)

[[[ 1  3]
  [ 9 11]]

 [[ 8  4]
  [ 6  3]]]


# Initializing different types of array

In [36]:
#All 0's matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
#All 1's matrix
np.ones((4,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [40]:
#Any other number
np.full((2,3), 27)

array([[27, 27, 27],
       [27, 27, 27]])

In [43]:
#Any other number (full_like)

np.full_like(b,30)

array([[30., 30., 30., 30.],
       [30., 30., 30., 30.]])

In [50]:
#Random decimal numbers
np.random.rand(4,2,2,3)

array([[[[0.33954035, 0.7111475 , 0.25726567],
         [0.78684742, 0.83028866, 0.74442281]],

        [[0.62662178, 0.2552762 , 0.94016687],
         [0.34458701, 0.54815044, 0.54643465]]],


       [[[0.53624659, 0.26413813, 0.45115644],
         [0.08612094, 0.33846606, 0.75216943]],

        [[0.81220598, 0.25200663, 0.64823596],
         [0.24219158, 0.73271963, 0.29227307]]],


       [[[0.43002298, 0.52521649, 0.98299609],
         [0.69662032, 0.12448493, 0.36576217]],

        [[0.8885904 , 0.67433936, 0.46170987],
         [0.41124348, 0.08298716, 0.46070427]]],


       [[[0.54259028, 0.24118736, 0.9088011 ],
         [0.67575324, 0.4683394 , 0.63102178]],

        [[0.04414628, 0.84879681, 0.60591598],
         [0.54942578, 0.2143677 , 0.35438896]]]])

In [53]:
#Random integers
np.random.randint(-2,7, size=(3,3))

array([[ 1, -2,  0],
       [ 1,  4,  1],
       [-2,  2,  0]])

In [54]:
#the identity ,matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
#Repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [66]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [83]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
print(z)
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [90]:
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copying an array

In [95]:
a=np.array([1,2,3])
b=a.copy()

b[1]=100
print(b)

[  1 100   3]


# Mathematics

In [96]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [97]:
a+2

array([3, 4, 5, 6])

In [98]:
a-2

array([-1,  0,  1,  2])

In [99]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [100]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [101]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [103]:
b=np.array([1,2,0,1])

a+b

array([2, 4, 3, 5])

In [105]:
#Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [106]:
#For lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear algebra

In [118]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [123]:
b1=np.full((3,4),2)
print(b)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [124]:
np.matmul(a,b1)

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [125]:
#Find the determinant of the matrix
c=np.identity(3)
np.linalg.det(c)

1.0

# Stastics

In [129]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [130]:
np.min(stats)

1

In [131]:
np.max(stats)

6

In [133]:
np.max(stats, axis=1)

array([3, 6])

In [134]:
np.max(stats, axis=0)

array([4, 5, 6])

In [135]:
np.sum(stats)

21

In [137]:
np.sum(stats, axis=1)

array([ 6, 15])

# Reorganizing arrays

In [143]:
before = np.array([[1,2,3,9],[4,5,6,7]])
print(before)

[[1 2 3 9]
 [4 5 6 7]]


In [146]:
after=before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 9]]

 [[4 5]
  [6 7]]]


In [148]:
#Vertical stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [153]:
#Horizontal Stack

h1=np.zeros((2,3))
h2=np.ones((2,4))

np.hstack([h1,h2,h1,h2])

array([[0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.]])

# Miscellanious

In [164]:
#Load data from files

filedata = np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[ 1 13 24  2 33 24  5 65  7 58 95]
 [ 4  7  9  2 47 94  3 25 23 55 89]
 [11 22 33 44 55 66 77 88 99 10 11]
 [21 31  3 45 67 65 43 21 85  5  6]]


# Boolean masking and advanced indexing

In [167]:
filedata>50

array([[False, False, False, False, False, False, False,  True, False,
         True,  True],
       [False, False, False, False, False,  True, False, False, False,
         True,  True],
       [False, False, False, False,  True,  True,  True,  True,  True,
        False, False],
       [False, False, False, False,  True,  True, False, False,  True,
        False, False]])

In [168]:
filedata[filedata>50]

array([65, 58, 95, 94, 55, 89, 55, 66, 77, 88, 99, 67, 65, 85])

In [170]:
#you can index with list in numpy

a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,8]]

array([2, 4, 9])

In [171]:
np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [172]:
np.all(filedata>50, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [173]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False, False, False,  True, False,
         True,  True],
       [False, False, False, False, False,  True, False, False, False,
         True,  True],
       [False, False, False, False,  True,  True,  True,  True,  True,
        False, False],
       [False, False, False, False,  True,  True, False, False,  True,
        False, False]])

In [174]:
(~((filedata>50) & (filedata<100)))

array([[ True,  True,  True,  True,  True,  True,  True, False,  True,
        False, False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
        False, False],
       [ True,  True,  True,  True, False, False, False, False, False,
         True,  True],
       [ True,  True,  True,  True, False, False,  True,  True, False,
         True,  True]])